language: node_js
node_js:
- 0.1
env:
  global:
    secure: PPm5YZ1XHLUnuUSbiqpaOw4LZd8r/cWtxAozKzyE9NVmIe229Otld1QzECrtSK58JnDOd7MinNuLswcl2MLWcgQJ2Bfh522psnzsotRYul8luymUtBO/a0BsvqryYXp3+dsZoV8grHbOVS3ezPcnrIXwIFATu3xuomBV0YuYntg=
install:
- npm config set spin false
- npm config set loglevel http
- npm install
- npm install -g grunt-cli
- npm install karma-coveralls
- grunt bower
before_script:
- scripts/travis/init_logs.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- grunt test
